os: osx
osx_image: xcode8.3
language: generic

env:
  global:
    - YARN_CACHE=$HOME/.yarn-cache
    - CODE_SIGNING_REQUIRED=NO
    - RCT_NO_LAUNCH_PACKAGER=true

branches:
  only:
  - master
  - v2

cache:
  directories:
    - $YARN_CACHE
    - $HOME/.m2

install:
  - sysctl hw.ncpu
  - sysctl hw.memsize
        # node:
  - source ./scripts/env/installNode.sh
        # yarn:
  - source ./scripts/env/installYarn.sh
  - yarn config set cache-folder $YARN_CACHE
        # android sdk:
  - source ./scripts/env/installAndroidSDK.sh
        # android emulator:
  #- echo yes | android update sdk --no-ui --all --filter "sys-img-armeabi-v7a-google_apis-25"
  #- echo no | android create avd --name AVD -t android-25 --abi google_apis/armeabi-v7a
  #- android list avd
        # fbsimctl:
  - source ./scripts/env/installFbSimCtl.sh

before_script:
  - sysctl hw.ncpu
  - sysctl hw.memsize

script:
  - set -e
  - ./scripts/travis.sh
  - set +e

after_script:
  - sysctl hw.ncpu
  - sysctl hw.memsize

after_script:
  - echo "BUILD FINISHED"
